Repository furrer-lab/abn, pull requests merged in 2024-09, with the labels that each got.

#151 temporal fix for dependency build `ragg`
  .github/workflows/Fedora_setup.yml
  .github/workflows/Macos_setup.yml
  .github/workflows/Ubuntu_setup.yml
  .github/workflows/Windows_setup.yml
  README.md
Labels: good first issue, help wanted

#157 152 paper submission next steps
  .github/workflows/build-joss-paper.yml
  vignettes/paper.bib
Labels: documentation, pkgdown::passed

#160 159 capitalization in paper references
  inst/CITATION
  vignettes/benchmarkBoxPlot-1.png
  vignettes/data_simulation.Rmd
  vignettes/paper.bib
Labels: URL::passed, CRAN::failed, pkgdown::passed, CompVignettes::passed
