Repository furrer-lab/abn, pull requests merged in 2024-05, with the labels that each got.

#88 updated development environment to R 4.4.0 including all packages rec…
  man/abn-package.Rd
  renv.lock
  renv/activate.R
Labels: enhancement

#89 26 tests tracking memory usage the slow pipeline
  .github/workflows/memory_checks.yml
  .github/workflows/pkgdown_checks.yml
  CONTRIBUTING.md
Labels: memory::check

#103 101 add chglog and linter configurations to rbuildignore
  .Rbuildignore
  .lintr
  README.md
Labels: enhancement, linting::failed, URL::passed, CRAN::passed

#112 fix: fetching correct tag for previous version
  .github/workflows/initiate_version_release.yml
  .github/workflows/publish_version_enforce.yml
  .github/workflows/publish_version_merging.yml
Labels: bug, CRAN::passed
